[package]
name = "hotkey-daemon"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
evdev = "0.13"
nix = { version = "0.30", features = ["user"] }
# log = "0.4"
clap = { version = "4.5", features = ["derive"] } # cli args parser
